// Test generated by LLM

import { Queue } from "bullmq";
import Redis from "ioredis";
import dotenv from "dotenv";
dotenv.config();

const connection = new Redis(process.env.REDIS_URL, { maxRetriesPerRequest: null });
const queue = new Queue("mcp-commands", { connection });
const redis = connection;

async function main(){
  const cmd = process.argv.slice(2).join(" ") || "echo hello from mcp test";
  console.log("Enqueuing command:", cmd);
  const job = await queue.add("run", { command: cmd }, { removeOnComplete: false, removeOnFail: false });
  console.log("Job added:", job.id);

  // Poll for result up to 30 seconds
  const key = `mcp:jobresult:${job.id}`;
  const deadline = Date.now() + 30000;
  while(Date.now() < deadline){
    const data = await redis.get(key);
    if (data) {
      console.log("Job result found:");
      try {
        const parsed = JSON.parse(data);
        console.log(JSON.stringify(parsed, null, 2));
      } catch(e){
        console.log("Raw data:", data);
      }
      await redis.quit();
      return;
    }
    await new Promise(r => setTimeout(r, 1000));
  }
  console.log("Timed out waiting for job result. JobId:", job.id);
  await redis.quit();
}

main().catch(err=>{
  console.error("ERROR:", err);
  process.exit(1);
});
